version: '3'

services:
  bot:
    build: .
    image: marketing-bot
    container_name: marketing-bot
    volumes:
       - .:/usr/app
       - /usr/app/node_modules
    working_dir: /usr/app
    command: npm run start:dev

